language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    update: true
    packages:
      - acl

install:
  - composer self-update 1.10.15
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/grumphp run
